import { afterEach, expect, it, vi } from "vitest";
import { render } from "vitest-browser-svelte";
import { page } from "vitest/browser";
import type { Id } from "../../../../convex/_generated/dataModel";
import AgentChatPanel from "./AgentChatPanel.svelte";
import { ATTEMPT_BATCH_LIMIT } from "$lib/uploads/outboxFlush";
import { __resetAuthState } from "$lib/test/convex-auth-stub";
import { __resetConvexStub, __setQueryData, __setPaginatedRows, __setMutationResult, __mutationCalls } from "$lib/test/convex-svelte-stub.svelte";
afterEach(() => vi.restoreAllMocks());
it("does not register later upload batches after the owning project changes", async () => {
  __resetConvexStub(); __resetAuthState(); localStorage.clear();
  for (const name of ["chatV2:listThreads", "chatV2:listTurns", "chatV2:listProposals", "research:listSessions"]) __setQueryData(name, []);
  __setQueryData("chatV2:listMessages", { streams: { kind: "list", messages: [] } });
  __setPaginatedRows("chatV2:listMessages", []);
  let finish: (value: null) => void = () => {};
  __setMutationResult("uploadAttempts:recordUploadAttempts", new Promise(resolve => { finish = resolve; }));
  vi.spyOn(console, "error").mockImplementation(() => {});
  const view = await render(AgentChatPanel, { projectId: "project-before" as Id<"projects">, reportId: "report-before" as Id<"reports"> });
  const input = document.querySelector('input[type="file"][multiple]');
  if (!(input instanceof HTMLInputElement)) throw new Error("Upload input missing");
  const files = new DataTransfer();
  for (let index = 0; index <= ATTEMPT_BATCH_LIMIT; index++) files.items.add(new File(["text"], `notes-${index}.txt`));
  input.files = files.files; input.dispatchEvent(new Event("change", { bubbles: true }));
  await page.getByRole("button", { name: "Writer's notes", exact: true }).click();
  await expect.poll(() => __mutationCalls("uploadAttempts:recordUploadAttempts").length).toBe(1);
  await view.rerender({ projectId: "project-after" as Id<"projects">, reportId: "report-after" as Id<"reports"> });
  finish(null);
  await new Promise(resolve => setTimeout(resolve, 100));
  expect(__mutationCalls("uploadAttempts:recordUploadAttempts")).toHaveLength(1);
  expect(__mutationCalls("documents:uploadDocument")).toEqual([]);
  expect(__mutationCalls("documents:generateUploadUrl")).toEqual([]);
});
