/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ai_actionDeadline from "../ai/actionDeadline.js";
import type * as ai_analyzerAgent from "../ai/analyzerAgent.js";
import type * as ai_brain_embeddings from "../ai/brain/embeddings.js";
import type * as ai_brain_erase from "../ai/brain/erase.js";
import type * as ai_brain_ingest from "../ai/brain/ingest.js";
import type * as ai_brain_query from "../ai/brain/query.js";
import type * as ai_brain_rag from "../ai/brain/rag.js";
import type * as ai_brain_retrieve from "../ai/brain/retrieve.js";
import type * as ai_brain_scienceRouting from "../ai/brain/scienceRouting.js";
import type * as ai_brainRetrieval from "../ai/brainRetrieval.js";
import type * as ai_brief from "../ai/brief.js";
import type * as ai_changelogPipeline from "../ai/changelogPipeline.js";
import type * as ai_chatAgentV2 from "../ai/chatAgentV2.js";
import type * as ai_chatEvidence from "../ai/chatEvidence.js";
import type * as ai_chronologyAgent from "../ai/chronologyAgent.js";
import type * as ai_condense from "../ai/condense.js";
import type * as ai_condenseAgent from "../ai/condenseAgent.js";
import type * as ai_financialAgent from "../ai/financialAgent.js";
import type * as ai_instrument from "../ai/instrument.js";
import type * as ai_iterative from "../ai/iterative.js";
import type * as ai_learning from "../ai/learning.js";
import type * as ai_model from "../ai/model.js";
import type * as ai_modelEvalSet from "../ai/modelEvalSet.js";
import type * as ai_modelEvaluation from "../ai/modelEvaluation.js";
import type * as ai_modelFeedback from "../ai/modelFeedback.js";
import type * as ai_openrouter from "../ai/openrouter.js";
import type * as ai_openrouterCore from "../ai/openrouterCore.js";
import type * as ai_orderedGeneration from "../ai/orderedGeneration.js";
import type * as ai_pipeline from "../ai/pipeline.js";
import type * as ai_placeholderClient from "../ai/placeholderClient.js";
import type * as ai_postQa from "../ai/postQa.js";
import type * as ai_promptDefinitions from "../ai/promptDefinitions.js";
import type * as ai_promptProgram from "../ai/promptProgram.js";
import type * as ai_prompts from "../ai/prompts.js";
import type * as ai_providers from "../ai/providers.js";
import type * as ai_qaAgent from "../ai/qaAgent.js";
import type * as ai_qaChecks from "../ai/qaChecks.js";
import type * as ai_reasoningSignature from "../ai/reasoningSignature.js";
import type * as ai_research_actions from "../ai/research/actions.js";
import type * as ai_research_core from "../ai/research/core.js";
import type * as ai_research_manager from "../ai/research/manager.js";
import type * as ai_research_openrouter from "../ai/research/openrouter.js";
import type * as ai_research_workflow from "../ai/research/workflow.js";
import type * as ai_reviewAgent from "../ai/reviewAgent.js";
import type * as ai_section242Agent from "../ai/section242Agent.js";
import type * as ai_section244Agent from "../ai/section244Agent.js";
import type * as ai_section246Agent from "../ai/section246Agent.js";
import type * as ai_seeds from "../ai/seeds.js";
import type * as ai_selfCheck from "../ai/selfCheck.js";
import type * as ai_speakerRolesAgent from "../ai/speakerRolesAgent.js";
import type * as ai_structured from "../ai/structured.js";
import type * as ai_styleAnalysis from "../ai/styleAnalysis.js";
import type * as ai_transcriptFactsAgent from "../ai/transcriptFactsAgent.js";
import type * as ai_trustedContext from "../ai/trustedContext.js";
import type * as ai_writerSettings from "../ai/writerSettings.js";
import type * as ai_writerStyle from "../ai/writerStyle.js";
import type * as aiUsage from "../aiUsage.js";
import type * as appSettings from "../appSettings.js";
import type * as auth from "../auth.js";
import type * as brain from "../brain.js";
import type * as briefs from "../briefs.js";
import type * as changelog from "../changelog.js";
import type * as chat from "../chat.js";
import type * as chatFeedback from "../chatFeedback.js";
import type * as chatV2 from "../chatV2.js";
import type * as comments from "../comments.js";
import type * as comparisons from "../comparisons.js";
import type * as complianceNotes from "../complianceNotes.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardBackfill from "../dashboardBackfill.js";
import type * as debugTools from "../debugTools.js";
import type * as documents from "../documents.js";
import type * as emailMigration from "../emailMigration.js";
import type * as errorReports from "../errorReports.js";
import type * as financial from "../financial.js";
import type * as generations from "../generations.js";
import type * as houseStyle from "../houseStyle.js";
import type * as http from "../http.js";
import type * as ingestion from "../ingestion.js";
import type * as ingestionPort from "../ingestionPort.js";
import type * as ingestionSync from "../ingestionSync.js";
import type * as invites from "../invites.js";
import type * as learning from "../learning.js";
import type * as learningHealth from "../learningHealth.js";
import type * as lib_activeGeneration from "../lib/activeGeneration.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_briefInputsHash from "../lib/briefInputsHash.js";
import type * as lib_briefRender from "../lib/briefRender.js";
import type * as lib_chatPublicOutput from "../lib/chatPublicOutput.js";
import type * as lib_citationSpeakers from "../lib/citationSpeakers.js";
import type * as lib_citations from "../lib/citations.js";
import type * as lib_claimExclusionMatcher from "../lib/claimExclusionMatcher.js";
import type * as lib_comparisonText from "../lib/comparisonText.js";
import type * as lib_completionReport from "../lib/completionReport.js";
import type * as lib_complianceNote from "../lib/complianceNote.js";
import type * as lib_contextInclusion from "../lib/contextInclusion.js";
import type * as lib_contracts from "../lib/contracts.js";
import type * as lib_dashboardProjection from "../lib/dashboardProjection.js";
import type * as lib_deidentify from "../lib/deidentify.js";
import type * as lib_deviationInventory from "../lib/deviationInventory.js";
import type * as lib_draftingInputsFailure from "../lib/draftingInputsFailure.js";
import type * as lib_editDistance from "../lib/editDistance.js";
import type * as lib_eligibleOwner from "../lib/eligibleOwner.js";
import type * as lib_email from "../lib/email.js";
import type * as lib_frozenWriterStyle from "../lib/frozenWriterStyle.js";
import type * as lib_gatedWorkflow from "../lib/gatedWorkflow.js";
import type * as lib_generationIndexReads from "../lib/generationIndexReads.js";
import type * as lib_generationOutputs from "../lib/generationOutputs.js";
import type * as lib_generationProgress from "../lib/generationProgress.js";
import type * as lib_generationTransitions from "../lib/generationTransitions.js";
import type * as lib_generations_brief from "../lib/generations/brief.js";
import type * as lib_generations_candidates from "../lib/generations/candidates.js";
import type * as lib_generations_chain from "../lib/generations/chain.js";
import type * as lib_generations_draftingInputs from "../lib/generations/draftingInputs.js";
import type * as lib_generations_inputs from "../lib/generations/inputs.js";
import type * as lib_generations_iterative from "../lib/generations/iterative.js";
import type * as lib_generations_lifecycle from "../lib/generations/lifecycle.js";
import type * as lib_generations_migrations from "../lib/generations/migrations.js";
import type * as lib_generations_postQa from "../lib/generations/postQa.js";
import type * as lib_generations_projection from "../lib/generations/projection.js";
import type * as lib_generations_reapers from "../lib/generations/reapers.js";
import type * as lib_generations_redraft from "../lib/generations/redraft.js";
import type * as lib_generations_reservation from "../lib/generations/reservation.js";
import type * as lib_generations_scoring from "../lib/generations/scoring.js";
import type * as lib_generations_seedGuards from "../lib/generations/seedGuards.js";
import type * as lib_generations_seedStage from "../lib/generations/seedStage.js";
import type * as lib_glossaryMatcher from "../lib/glossaryMatcher.js";
import type * as lib_ingestionClassify from "../lib/ingestionClassify.js";
import type * as lib_learningAdmission from "../lib/learningAdmission.js";
import type * as lib_learningHealthReads from "../lib/learningHealthReads.js";
import type * as lib_lineLimits from "../lib/lineLimits.js";
import type * as lib_modelCatalogRefs from "../lib/modelCatalogRefs.js";
import type * as lib_modelCatalogValidators from "../lib/modelCatalogValidators.js";
import type * as lib_modelRoles from "../lib/modelRoles.js";
import type * as lib_orderedChain from "../lib/orderedChain.js";
import type * as lib_orderedPayloadStore from "../lib/orderedPayloadStore.js";
import type * as lib_ownerMatching from "../lib/ownerMatching.js";
import type * as lib_passageEdits from "../lib/passageEdits.js";
import type * as lib_projectDeletion from "../lib/projectDeletion.js";
import type * as lib_projectScopedTables from "../lib/projectScopedTables.js";
import type * as lib_providerConfig from "../lib/providerConfig.js";
import type * as lib_purgeBudget from "../lib/purgeBudget.js";
import type * as lib_qaFindings from "../lib/qaFindings.js";
import type * as lib_qaResults from "../lib/qaResults.js";
import type * as lib_readBudget from "../lib/readBudget.js";
import type * as lib_reportEdits from "../lib/reportEdits.js";
import type * as lib_rerankTelemetry from "../lib/rerankTelemetry.js";
import type * as lib_roleCapabilities from "../lib/roleCapabilities.js";
import type * as lib_safeErrorDetails from "../lib/safeErrorDetails.js";
import type * as lib_sectionRunData from "../lib/sectionRunData.js";
import type * as lib_seedApproval from "../lib/seedApproval.js";
import type * as lib_seedContract from "../lib/seedContract.js";
import type * as lib_seedDecisionState from "../lib/seedDecisionState.js";
import type * as lib_seedDecisionWrites from "../lib/seedDecisionWrites.js";
import type * as lib_seedDispatch from "../lib/seedDispatch.js";
import type * as lib_seedFacts from "../lib/seedFacts.js";
import type * as lib_seedLearningHealth from "../lib/seedLearningHealth.js";
import type * as lib_seedReaders from "../lib/seedReaders.js";
import type * as lib_seedReadiness from "../lib/seedReadiness.js";
import type * as lib_seedRevisions from "../lib/seedRevisions.js";
import type * as lib_seedSnapshotLoader from "../lib/seedSnapshotLoader.js";
import type * as lib_selfCheckRules from "../lib/selfCheckRules.js";
import type * as lib_settingsDocument from "../lib/settingsDocument.js";
import type * as lib_settingsExtraction from "../lib/settingsExtraction.js";
import type * as lib_snapshots from "../lib/snapshots.js";
import type * as lib_storage from "../lib/storage.js";
import type * as lib_storylineQuestionNote from "../lib/storylineQuestionNote.js";
import type * as lib_styleOverrides from "../lib/styleOverrides.js";
import type * as lib_successMetrics from "../lib/successMetrics.js";
import type * as lib_teamRoster from "../lib/teamRoster.js";
import type * as lib_tiptapReport from "../lib/tiptapReport.js";
import type * as lib_transcriptFactRows from "../lib/transcriptFactRows.js";
import type * as lib_transcriptFacts from "../lib/transcriptFacts.js";
import type * as lib_transcriptPlaceholders from "../lib/transcriptPlaceholders.js";
import type * as lib_transcriptSpeakers from "../lib/transcriptSpeakers.js";
import type * as lib_transcriptStructure from "../lib/transcriptStructure.js";
import type * as lib_transcriptValidators from "../lib/transcriptValidators.js";
import type * as lib_transcripts from "../lib/transcripts.js";
import type * as lib_uploadAttempts from "../lib/uploadAttempts.js";
import type * as lib_workItemOversight from "../lib/workItemOversight.js";
import type * as modelCatalog from "../modelCatalog.js";
import type * as myWork from "../myWork.js";
import type * as myWorkBackfill from "../myWorkBackfill.js";
import type * as myWorkOps from "../myWorkOps.js";
import type * as oversight from "../oversight.js";
import type * as ownerBackfill from "../ownerBackfill.js";
import type * as pdReviews from "../pdReviews.js";
import type * as projectActivity from "../projectActivity.js";
import type * as projectCreation from "../projectCreation.js";
import type * as projectDuplication from "../projectDuplication.js";
import type * as projectEvidence from "../projectEvidence.js";
import type * as projectWorkflow from "../projectWorkflow.js";
import type * as projects from "../projects.js";
import type * as providerReadiness from "../providerReadiness.js";
import type * as reportEditDistance from "../reportEditDistance.js";
import type * as reportViews from "../reportViews.js";
import type * as reports from "../reports.js";
import type * as research from "../research.js";
import type * as reviewFromProject from "../reviewFromProject.js";
import type * as reviews from "../reviews.js";
import type * as scienceCodeSuggestions from "../scienceCodeSuggestions.js";
import type * as seed from "../seed.js";
import type * as seedRuns from "../seedRuns.js";
import type * as seeds from "../seeds.js";
import type * as snapshots from "../snapshots.js";
import type * as tags from "../tags.js";
import type * as testFixtureRows from "../testFixtureRows.js";
import type * as transcriptDigests from "../transcriptDigests.js";
import type * as transcripts from "../transcripts.js";
import type * as uploadAttempts from "../uploadAttempts.js";
import type * as users from "../users.js";
import type * as workItems from "../workItems.js";
import type * as workspaceRollout from "../workspaceRollout.js";
import type * as writerProfiles from "../writerProfiles.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "ai/actionDeadline": typeof ai_actionDeadline;
  "ai/analyzerAgent": typeof ai_analyzerAgent;
  "ai/brain/embeddings": typeof ai_brain_embeddings;
  "ai/brain/erase": typeof ai_brain_erase;
  "ai/brain/ingest": typeof ai_brain_ingest;
  "ai/brain/query": typeof ai_brain_query;
  "ai/brain/rag": typeof ai_brain_rag;
  "ai/brain/retrieve": typeof ai_brain_retrieve;
  "ai/brain/scienceRouting": typeof ai_brain_scienceRouting;
  "ai/brainRetrieval": typeof ai_brainRetrieval;
  "ai/brief": typeof ai_brief;
  "ai/changelogPipeline": typeof ai_changelogPipeline;
  "ai/chatAgentV2": typeof ai_chatAgentV2;
  "ai/chatEvidence": typeof ai_chatEvidence;
  "ai/chronologyAgent": typeof ai_chronologyAgent;
  "ai/condense": typeof ai_condense;
  "ai/condenseAgent": typeof ai_condenseAgent;
  "ai/financialAgent": typeof ai_financialAgent;
  "ai/instrument": typeof ai_instrument;
  "ai/iterative": typeof ai_iterative;
  "ai/learning": typeof ai_learning;
  "ai/model": typeof ai_model;
  "ai/modelEvalSet": typeof ai_modelEvalSet;
  "ai/modelEvaluation": typeof ai_modelEvaluation;
  "ai/modelFeedback": typeof ai_modelFeedback;
  "ai/openrouter": typeof ai_openrouter;
  "ai/openrouterCore": typeof ai_openrouterCore;
  "ai/orderedGeneration": typeof ai_orderedGeneration;
  "ai/pipeline": typeof ai_pipeline;
  "ai/placeholderClient": typeof ai_placeholderClient;
  "ai/postQa": typeof ai_postQa;
  "ai/promptDefinitions": typeof ai_promptDefinitions;
  "ai/promptProgram": typeof ai_promptProgram;
  "ai/prompts": typeof ai_prompts;
  "ai/providers": typeof ai_providers;
  "ai/qaAgent": typeof ai_qaAgent;
  "ai/qaChecks": typeof ai_qaChecks;
  "ai/reasoningSignature": typeof ai_reasoningSignature;
  "ai/research/actions": typeof ai_research_actions;
  "ai/research/core": typeof ai_research_core;
  "ai/research/manager": typeof ai_research_manager;
  "ai/research/openrouter": typeof ai_research_openrouter;
  "ai/research/workflow": typeof ai_research_workflow;
  "ai/reviewAgent": typeof ai_reviewAgent;
  "ai/section242Agent": typeof ai_section242Agent;
  "ai/section244Agent": typeof ai_section244Agent;
  "ai/section246Agent": typeof ai_section246Agent;
  "ai/seeds": typeof ai_seeds;
  "ai/selfCheck": typeof ai_selfCheck;
  "ai/speakerRolesAgent": typeof ai_speakerRolesAgent;
  "ai/structured": typeof ai_structured;
  "ai/styleAnalysis": typeof ai_styleAnalysis;
  "ai/transcriptFactsAgent": typeof ai_transcriptFactsAgent;
  "ai/trustedContext": typeof ai_trustedContext;
  "ai/writerSettings": typeof ai_writerSettings;
  "ai/writerStyle": typeof ai_writerStyle;
  aiUsage: typeof aiUsage;
  appSettings: typeof appSettings;
  auth: typeof auth;
  brain: typeof brain;
  briefs: typeof briefs;
  changelog: typeof changelog;
  chat: typeof chat;
  chatFeedback: typeof chatFeedback;
  chatV2: typeof chatV2;
  comments: typeof comments;
  comparisons: typeof comparisons;
  complianceNotes: typeof complianceNotes;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dashboardBackfill: typeof dashboardBackfill;
  debugTools: typeof debugTools;
  documents: typeof documents;
  emailMigration: typeof emailMigration;
  errorReports: typeof errorReports;
  financial: typeof financial;
  generations: typeof generations;
  houseStyle: typeof houseStyle;
  http: typeof http;
  ingestion: typeof ingestion;
  ingestionPort: typeof ingestionPort;
  ingestionSync: typeof ingestionSync;
  invites: typeof invites;
  learning: typeof learning;
  learningHealth: typeof learningHealth;
  "lib/activeGeneration": typeof lib_activeGeneration;
  "lib/auth": typeof lib_auth;
  "lib/briefInputsHash": typeof lib_briefInputsHash;
  "lib/briefRender": typeof lib_briefRender;
  "lib/chatPublicOutput": typeof lib_chatPublicOutput;
  "lib/citationSpeakers": typeof lib_citationSpeakers;
  "lib/citations": typeof lib_citations;
  "lib/claimExclusionMatcher": typeof lib_claimExclusionMatcher;
  "lib/comparisonText": typeof lib_comparisonText;
  "lib/completionReport": typeof lib_completionReport;
  "lib/complianceNote": typeof lib_complianceNote;
  "lib/contextInclusion": typeof lib_contextInclusion;
  "lib/contracts": typeof lib_contracts;
  "lib/dashboardProjection": typeof lib_dashboardProjection;
  "lib/deidentify": typeof lib_deidentify;
  "lib/deviationInventory": typeof lib_deviationInventory;
  "lib/draftingInputsFailure": typeof lib_draftingInputsFailure;
  "lib/editDistance": typeof lib_editDistance;
  "lib/eligibleOwner": typeof lib_eligibleOwner;
  "lib/email": typeof lib_email;
  "lib/frozenWriterStyle": typeof lib_frozenWriterStyle;
  "lib/gatedWorkflow": typeof lib_gatedWorkflow;
  "lib/generationIndexReads": typeof lib_generationIndexReads;
  "lib/generationOutputs": typeof lib_generationOutputs;
  "lib/generationProgress": typeof lib_generationProgress;
  "lib/generationTransitions": typeof lib_generationTransitions;
  "lib/generations/brief": typeof lib_generations_brief;
  "lib/generations/candidates": typeof lib_generations_candidates;
  "lib/generations/chain": typeof lib_generations_chain;
  "lib/generations/draftingInputs": typeof lib_generations_draftingInputs;
  "lib/generations/inputs": typeof lib_generations_inputs;
  "lib/generations/iterative": typeof lib_generations_iterative;
  "lib/generations/lifecycle": typeof lib_generations_lifecycle;
  "lib/generations/migrations": typeof lib_generations_migrations;
  "lib/generations/postQa": typeof lib_generations_postQa;
  "lib/generations/projection": typeof lib_generations_projection;
  "lib/generations/reapers": typeof lib_generations_reapers;
  "lib/generations/redraft": typeof lib_generations_redraft;
  "lib/generations/reservation": typeof lib_generations_reservation;
  "lib/generations/scoring": typeof lib_generations_scoring;
  "lib/generations/seedGuards": typeof lib_generations_seedGuards;
  "lib/generations/seedStage": typeof lib_generations_seedStage;
  "lib/glossaryMatcher": typeof lib_glossaryMatcher;
  "lib/ingestionClassify": typeof lib_ingestionClassify;
  "lib/learningAdmission": typeof lib_learningAdmission;
  "lib/learningHealthReads": typeof lib_learningHealthReads;
  "lib/lineLimits": typeof lib_lineLimits;
  "lib/modelCatalogRefs": typeof lib_modelCatalogRefs;
  "lib/modelCatalogValidators": typeof lib_modelCatalogValidators;
  "lib/modelRoles": typeof lib_modelRoles;
  "lib/orderedChain": typeof lib_orderedChain;
  "lib/orderedPayloadStore": typeof lib_orderedPayloadStore;
  "lib/ownerMatching": typeof lib_ownerMatching;
  "lib/passageEdits": typeof lib_passageEdits;
  "lib/projectDeletion": typeof lib_projectDeletion;
  "lib/projectScopedTables": typeof lib_projectScopedTables;
  "lib/providerConfig": typeof lib_providerConfig;
  "lib/purgeBudget": typeof lib_purgeBudget;
  "lib/qaFindings": typeof lib_qaFindings;
  "lib/qaResults": typeof lib_qaResults;
  "lib/readBudget": typeof lib_readBudget;
  "lib/reportEdits": typeof lib_reportEdits;
  "lib/rerankTelemetry": typeof lib_rerankTelemetry;
  "lib/roleCapabilities": typeof lib_roleCapabilities;
  "lib/safeErrorDetails": typeof lib_safeErrorDetails;
  "lib/sectionRunData": typeof lib_sectionRunData;
  "lib/seedApproval": typeof lib_seedApproval;
  "lib/seedContract": typeof lib_seedContract;
  "lib/seedDecisionState": typeof lib_seedDecisionState;
  "lib/seedDecisionWrites": typeof lib_seedDecisionWrites;
  "lib/seedDispatch": typeof lib_seedDispatch;
  "lib/seedFacts": typeof lib_seedFacts;
  "lib/seedLearningHealth": typeof lib_seedLearningHealth;
  "lib/seedReaders": typeof lib_seedReaders;
  "lib/seedReadiness": typeof lib_seedReadiness;
  "lib/seedRevisions": typeof lib_seedRevisions;
  "lib/seedSnapshotLoader": typeof lib_seedSnapshotLoader;
  "lib/selfCheckRules": typeof lib_selfCheckRules;
  "lib/settingsDocument": typeof lib_settingsDocument;
  "lib/settingsExtraction": typeof lib_settingsExtraction;
  "lib/snapshots": typeof lib_snapshots;
  "lib/storage": typeof lib_storage;
  "lib/storylineQuestionNote": typeof lib_storylineQuestionNote;
  "lib/styleOverrides": typeof lib_styleOverrides;
  "lib/successMetrics": typeof lib_successMetrics;
  "lib/teamRoster": typeof lib_teamRoster;
  "lib/tiptapReport": typeof lib_tiptapReport;
  "lib/transcriptFactRows": typeof lib_transcriptFactRows;
  "lib/transcriptFacts": typeof lib_transcriptFacts;
  "lib/transcriptPlaceholders": typeof lib_transcriptPlaceholders;
  "lib/transcriptSpeakers": typeof lib_transcriptSpeakers;
  "lib/transcriptStructure": typeof lib_transcriptStructure;
  "lib/transcriptValidators": typeof lib_transcriptValidators;
  "lib/transcripts": typeof lib_transcripts;
  "lib/uploadAttempts": typeof lib_uploadAttempts;
  "lib/workItemOversight": typeof lib_workItemOversight;
  modelCatalog: typeof modelCatalog;
  myWork: typeof myWork;
  myWorkBackfill: typeof myWorkBackfill;
  myWorkOps: typeof myWorkOps;
  oversight: typeof oversight;
  ownerBackfill: typeof ownerBackfill;
  pdReviews: typeof pdReviews;
  projectActivity: typeof projectActivity;
  projectCreation: typeof projectCreation;
  projectDuplication: typeof projectDuplication;
  projectEvidence: typeof projectEvidence;
  projectWorkflow: typeof projectWorkflow;
  projects: typeof projects;
  providerReadiness: typeof providerReadiness;
  reportEditDistance: typeof reportEditDistance;
  reportViews: typeof reportViews;
  reports: typeof reports;
  research: typeof research;
  reviewFromProject: typeof reviewFromProject;
  reviews: typeof reviews;
  scienceCodeSuggestions: typeof scienceCodeSuggestions;
  seed: typeof seed;
  seedRuns: typeof seedRuns;
  seeds: typeof seeds;
  snapshots: typeof snapshots;
  tags: typeof tags;
  testFixtureRows: typeof testFixtureRows;
  transcriptDigests: typeof transcriptDigests;
  transcripts: typeof transcripts;
  uploadAttempts: typeof uploadAttempts;
  users: typeof users;
  workItems: typeof workItems;
  workspaceRollout: typeof workspaceRollout;
  writerProfiles: typeof writerProfiles;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  rag: import("@convex-dev/rag/_generated/component.js").ComponentApi<"rag">;
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  embedPool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"embedPool">;
  researchWorkflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"researchWorkflow">;
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
};
