import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const dir=path.dirname(new URL(import.meta.url).pathname);
const require=createRequire(path.join(process.cwd(),'package.json'));
const ts=require('typescript');
const {getSchema}=require('@tiptap/core');
const {Decoration,DecorationSet}=require('@tiptap/pm/view');
const hashes=JSON.parse(fs.readFileSync(path.join(dir,'hashes.json'),'utf8'));
for(const item of Object.values(hashes))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(dir,item.snapshot))).digest('hex'),item.sha256);
const read=name=>fs.readFileSync(path.join(dir,name+'.snapshot.txt'),'utf8');
const js=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const compile=source=>{const exports={};new Function('exports','require',js(source))(exports,require);return exports;};
const search=compile(read('docSearch.ts'));
const config=compile(read('tiptapConfig.ts'));
const editorSource=read('Editor.svelte');
const moduleSource=editorSource.match(/<script module lang="ts">([\s\S]*?)<\/script>/)[1];
const ast=ts.createSourceFile('editor.ts',moduleSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const printer=ts.createPrinter();
const stripped=ast.statements.filter(s=>!ts.isImportDeclaration(s)).map(s=>printer.printNode(ts.EmitHint.Unspecified,s,ast)).join('\n');
const helpers=new Function('Decoration','DecorationSet',...Object.keys(search),js(stripped)+';return {findAllInDoc,findTextInDoc,buildDecorationSet};')(Decoration,DecorationSet,...Object.values(search));
const instance=editorSource.match(/<script lang="ts">([\s\S]*?)<\/script>/)[1];
const instanceAst=ts.createSourceFile('instance.ts',instance,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const locate=instanceAst.statements.find(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='locateSectionParagraph');
assert.ok(locate);
const locateCode=js(printer.printNode(ts.EmitHint.Unspecified,locate,instanceAst));
const output=[];
for(const editable of [true,false]){
 const schema=getSchema(config.getEditorExtensions({editable}));
 const unicode=schema.node('doc',null,[schema.node('paragraph',null,schema.text('İİİİİİ'))]);unicode.check();
 const needle='\u0307i\u0307i';const actual=search.findOccurrencesBatch(unicode,[needle])[0];
 assert.deepEqual(actual,[{from:1,to:4,text:'İİİ'}]);
 const expected=[{from:1,to:4,text:'İİİ'},{from:4,to:7,text:'İİİ'}];
 const folded='İİİİİİ'.toLowerCase(); const candidateIndices=[];for(let at=folded.indexOf(needle);at!==-1;at=folded.indexOf(needle,at+1))candidateIndices.push(at);
 const doc=schema.node('doc',null,[schema.node('heading',{level:1},schema.text('242')),schema.node('paragraph',null,schema.text('alphabeta')),schema.node('paragraph',null,[schema.text('alpha'),schema.node('hardBreak'),schema.text('beta')])]);doc.check();
 const invoked=new Function('doc',`const exports={};const editor={state:{doc}};let aiHighlights=[];const scrolls=[];const scrollContainerToPos=(...args)=>scrolls.push(args);${locateCode};locateSectionParagraph('242',2);return {aiHighlights,scrolls};`)(doc);
 assert.deepEqual(invoked.aiHighlights,[{from:17,to:27,text:'alphabeta'}]);
 const target=invoked.aiHighlights[0];const validationText=search.extractMatchedText(doc,target.from,target.to);
 const fallback=helpers.findTextInDoc(doc,target.text,target.from);
 const decorations=helpers.buildDecorationSet(doc,[],invoked.aiHighlights).find().map(d=>({from:d.from,to:d.to,class:d.type.attrs.class}));
 assert.deepEqual(fallback,{from:6,to:15});assert.deepEqual(decorations,[{from:6,to:15,class:'ai-ref-highlight'}]);
 output.push({editable,unicode:{document:unicode.toJSON(),needle,folded,candidateIndices,returned:actual,expected,missingExpectedSecond:true},paragraph:{document:doc.toJSON(),section:'242',requestedParagraph:2,actualLocateInvocation:invoked,validationText,validationPasses:validationText===target.text,fallback,actualDecorations:decorations}});
}
console.log(JSON.stringify({method:'Frozen reviewed B13-r1 sources; actual AST-extracted locateSectionParagraph and buildDecorationSet; installed real schemas and DecorationSet; no browser/test runner',node:process.version,hashes,output},null,2));
