import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const dir=path.dirname(new URL(import.meta.url).pathname);
const require=createRequire(path.join(process.cwd(),'package.json'));
const ts=require('typescript');
const {getSchema}=require('@tiptap/core');
const {Decoration,DecorationSet}=require('@tiptap/pm/view');
const hashes=JSON.parse(fs.readFileSync(path.join(dir,'hashes.json'),'utf8'));
for(const item of Object.values(hashes))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(dir,item.snapshot))).digest('hex'),item.sha256);
const read=name=>fs.readFileSync(path.join(dir,name+'.snapshot.txt'),'utf8');
const js=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const compile=source=>{const exports={};new Function('exports','require',js(source))(exports,require);return exports;};
const search=compile(read('docSearch.ts'));
const config=compile(read('tiptapConfig.ts'));
const editorSource=read('Editor.svelte');
const moduleSource=editorSource.match(/<script module lang="ts">([\s\S]*?)<\/script>/)[1];
const ast=ts.createSourceFile('editor.ts',moduleSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const printer=ts.createPrinter();
const stripped=ast.statements.filter(s=>!ts.isImportDeclaration(s)).map(s=>printer.printNode(ts.EmitHint.Unspecified,s,ast)).join('\n');
const helpers=new Function('Decoration','DecorationSet',...Object.keys(search),js(stripped)+';return {findAllInDoc,findTextInDoc,buildDecorationSet};')(Decoration,DecorationSet,...Object.values(search));
const instance=editorSource.match(/<script lang="ts">([\s\S]*?)<\/script>/)[1];
const instanceAst=ts.createSourceFile('instance.ts',instance,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);
const highlight=instanceAst.statements.find(s=>ts.isFunctionDeclaration(s)&&s.name?.text==='highlightText');
assert.ok(highlight);
const highCode=js(printer.printNode(ts.EmitHint.Unspecified,highlight,instanceAst));
const output=[];
for(const editable of [true,false]){
 const schema=getSchema(config.getEditorExtensions({editable}));
 const unicode=schema.node('doc',null,[schema.node('paragraph',null,schema.text('İİİ'))]);unicode.check();
 const needle='\u0307i';const actual=search.findOccurrencesBatch(unicode,[needle])[0];
 assert.deepEqual(actual,[{from:1,to:3,text:'İİ'},{from:2,to:4,text:'İİ'}]);
 const doc=schema.node('doc',null,[schema.node('paragraph',null,schema.text('alphabeta')),schema.node('paragraph',null,[schema.text('alpha'),schema.node('hardBreak'),schema.text('beta')])]);doc.check();
 const located=helpers.findAllInDoc(doc,'alpha beta');
 assert.deepEqual(located,[{from:12,to:22,text:'alphabeta'}]);
 const validationText=search.extractMatchedText(doc,located[0].from,located[0].to);
 const fallback=helpers.findTextInDoc(doc,located[0].text,located[0].from);
 const decorations=helpers.buildDecorationSet(doc,[],located).find().map(d=>({from:d.from,to:d.to,class:d.type.attrs.class}));
 assert.deepEqual(fallback,{from:1,to:10});assert.deepEqual(decorations,[{from:1,to:10,class:'ai-ref-highlight'}]);
 const invoked=new Function('findAllInDoc','doc',`const exports={};const editor={state:{doc}};let aiHighlights=[];const scrolls=[];const scrollContainerToPos=(...args)=>scrolls.push(args);${highCode};highlightText(['alpha beta']);return {aiHighlights,scrolls};`)(helpers.findAllInDoc,doc);
 assert.deepEqual(invoked.aiHighlights,located);
 output.push({editable,unicode:{document:unicode.toJSON(),needle,returned:actual,overlap:actual[1].from<actual[0].to},hardBreak:{document:doc.toJSON(),requested:'alpha beta',located,validationText,validationPasses:validationText===located[0].text,fallback,actualDecorations:decorations,actualHighlightTextInvocation:invoked}});
}
console.log(JSON.stringify({method:'Frozen actual sources, AST-extracted actual Editor functions including highlightText and buildDecorationSet; installed real Tiptap schema/PM DecorationSet, no browser/test runner',node:process.version,hashes,output},null,2));
