import { beforeEach, expect, it } from "vitest";
import { page } from "vitest/browser";
import { render } from "vitest-browser-svelte";
import LogsPanel from "./LogsPanel.svelte";
import FilingReadinessPanel from "$lib/components/evidence/FilingReadinessPanel.svelte";
import type { Id } from "../../../../convex/_generated/dataModel";
import { __resetConvexStub, __setQueryData, __setQueryError, __activeQueryCount } from "$lib/test/convex-svelte-stub.svelte";
const projectId = "project-1" as Id<"projects">;
beforeEach(() => { __resetConvexStub(); });
it("leaves logs unsubscribed until open and reports loading instead of a fabricated empty count", async () => {
  await render(LogsPanel, { projectId });
  expect(__activeQueryCount("chat:listProjectLog")).toBe(0);
  await expect.element(page.getByRole("button", { name: "Logs", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Logs", exact: true }).click();
  await expect.element(page.getByRole("status")).toHaveTextContent("Loading logs");
  expect(__activeQueryCount("chat:listProjectLog")).toBe(1);
  __setQueryData("chat:listProjectLog", [{ _id: "log-1", role: "writer", content: "Recorded question", createdAt: 1 }]);
  await expect.element(page.getByText("Recorded question", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: /Logs/ }).click();
  await expect.element(page.getByRole("button", { name: /1 entry/ })).toBeVisible();
  expect(__activeQueryCount("chat:listProjectLog")).toBe(1);
});
it("keeps filing readiness live while details wait, then retains the evidence draft", async () => {
  __setQueryData("projectEvidence:getReadiness", { ready: false, blockers: [{ code: "ATTESTATION_REQUIRED", message: "Attestation required" }] });
  await render(FilingReadinessPanel, { projectId, reportId: "report-1" as Id<"reports">, clientName: "Acme", userRole: "writer" });
  expect(__activeQueryCount("projectEvidence:getReadiness")).toBe(1);
  expect(__activeQueryCount("projectEvidence:listEvidence")).toBe(0);
  expect(__activeQueryCount("reports:getProvenance")).toBe(0);
  expect(__activeQueryCount("documents:listDocuments")).toBe(0);
  const toggle = page.getByRole("button", { name: /Filing readiness/ });
  await expect.element(toggle).toHaveTextContent("1 blocker");
  await toggle.click();
  await expect.element(page.getByRole("status")).toHaveTextContent("Loading filing evidence");
  __setQueryData("projectEvidence:listEvidence", []);
  __setQueryData("reports:getProvenance", null);
  __setQueryData("documents:listDocuments", []);
  await page.getByRole("button", { name: "Add evidence", exact: true }).click();
  await page.getByRole("textbox", { name: "Source description" }).fill("Retained evidence draft");
  await toggle.click();
  await toggle.click();
  await expect.element(page.getByRole("textbox", { name: "Source description" })).toHaveValue("Retained evidence draft");
  expect(__activeQueryCount("projectEvidence:listEvidence")).toBe(1);
});

it("gives logs recovery guidance and shows a recovered subscription", async () => {
  __setQueryError("chat:listProjectLog", new Error("Unavailable"));
  await render(LogsPanel, { projectId });
  await page.getByRole("button", { name: "Logs", exact: true }).click();
  await expect.element(page.getByRole("alert")).toHaveTextContent("Reload the page to try again.");
  __setQueryError("chat:listProjectLog", undefined);
  __setQueryData("chat:listProjectLog", [{ _id: "recovered", role: "writer", content: "Recovered question", createdAt: 1 }]);
  await expect.element(page.getByText("Recovered question", { exact: true })).toBeVisible();
  await expect.element(page.getByRole("alert")).not.toBeInTheDocument();
});
it("gives filing evidence recovery guidance while preserving the readiness summary", async () => {
  __setQueryData("projectEvidence:getReadiness", { ready: false, blockers: [{ code: "ATTESTATION_REQUIRED", message: "Attestation required" }] });
  __setQueryData("projectEvidence:listEvidence", []);
  __setQueryData("reports:getProvenance", null);
  __setQueryError("documents:listDocuments", new Error("Unavailable"));
  await render(FilingReadinessPanel, { projectId, reportId: "report-1" as Id<"reports">, clientName: "Acme", userRole: "writer" });
  const toggle = page.getByRole("button", { name: /Filing readiness/ });
  await toggle.click();
  await expect.element(toggle).toHaveTextContent("1 blocker");
  await expect.element(page.getByRole("alert")).toHaveTextContent("Reload the page to try again.");
  __setQueryError("documents:listDocuments", undefined);
  __setQueryData("documents:listDocuments", []);
  await expect.element(page.getByRole("button", { name: "Add evidence", exact: true })).toBeVisible();
  await expect.element(page.getByRole("alert")).not.toBeInTheDocument();
});
